update

diff --git a/desktop/bin/gwt b/desktop/bin/gwt
--- a/desktop/bin/gwt
+++ b/desktop/bin/gwt
@@ -2,19 +2,6 @@
 
 ################################################################################
 #                                 FILE INFO
-# git worktree management
-################################################################################
-
-# should exit as soon as it encounters any non-zero exit code or usage of
-# undefined variables or failed piped commands
-# set -Eeuo pipefail
-  # change to local directory
-cd "$(dirname $0)"
-  # load lib
-. ../lib/lib_utils.sh
-# global variables
-LOG_LEVEL=3 # default is 1:NOTE
-
 # cli with boa
 CLI="""
 use: gwt
@@ -33,35 +20,47 @@ commands:
         type: string
   - use: switch
     short: switch to a specific worktree
+    aliases:
+      - s
     flags:
       - use: repo
         short: repository
         alias: r
         type: string
-      - use: branch
-        short: branch
-        alias: b
-        type: string
+      - use: main
+        short: switch to main branch
+        alias: m
+        type: bool
+      - use: work
+        short: search in work user
+        alias: w
+        type: bool
 
 """
-. ../lib/lib_cli.sh
+################################################################################
+
+# should exit as soon as it encounters any non-zero exit code or usage of
+# undefined variables or failed piped commands
+# set -Eeuo pipefail
+  # change to local directory
+cd "$(dirname $0)"
+  # load lib
+. ../lib/lib_utils.sh
+# global variables
+LOG_LEVEL=3 # default is 1:NOTE
 git_dir=~/gwt
 
+USER=marcelofpfelix
+WORK_REPO="team-telnyx"
+REPO_IGNORE='-not -path "./$WORK_REPO*"'
+
+
+
 gwt() {
-    log DEBG "$FUNCNAME: $*"
-    # if arguments over 1 run subcommand
-    if [ $# -gt 0 ]; then
-        $@
-    fi
+    help
 }
 
-clone() {
-    log DEBG "$FUNCNAME: $*"
-    # if arguments over 1
-    if [ $# -gt 0 ]; then
-        $@
-    fi
-
+gwt_clone() {
     # no subcommands, running the function
     repo_url="${ARGS[1]}"
     # print the result
@@ -106,33 +105,53 @@ clone() {
 }
 
 
-switch() {
-    log DEBG "$FUNCNAME: $*"
-    # if arguments over 1
-    if [ $# -gt 0 ]; then
-        $@
-    fi
+gwt_switch() {
 
     # no subcommands, running the function
     repo_url="${ARGS[1]}"
+    main="${ARGS[2]}"
+    work="${ARGS[3]}"
+    depth=3
+    user=""
+    ignore="$WORK_REPO"
+
     # print the result
-    log INFO "Running:" "${CMDS[@]}" "-r ${repo_url}" n:b:c:b:c
+    log INFO "Running:" "${CMDS[@]}" "-r ${repo_url}" "-m $main" "-w $work" n:b:c:b:c
 
-    if [ -z "$repo_url" ]; then
-        cd $git_dir
-        repo_url=$(find . -mindepth 3 -maxdepth 3 -type d -not -path "*.bare" -not -path "archive" -prune | fzf)
+    if [ "$main" = "true" ]; then
+      depth=2
     fi
+    if [ "$work" = "true" ]; then
+      ignore=$USER
+      user=$WORK_REPO
+      depth=2
+    fi
+# -printf "%P"
 
-    tmux new-window -n $repo_url -c $git_dir/$repo_url
+    #echo       find ./ -mindepth $depth -maxdepth $depth -type d -not -path "*.bare" -not -path "archive" -not -path "./$ignore*" -prune - fzf -q "$repo_url"
+#    if [ -z "$repo_url" ]; then
+    cd $git_dir/$user
+    repo_url=$(find ./ -mindepth $depth -maxdepth $depth -type d -not -path "*.bare" -not -path "archive" -not -path "./$ignore*" -prune  -printf "%P\n" | fzf -q "$repo_url")
+    [[ -z "$repo_url" ]] && exit 1
+#    fi
 
+#Notes="""
+#fzf --preview "bat --color=always --style=numbers --line-range=:500 {}"
+#"""
+
+    tmux new-window -n $repo_url -c $git_dir/$user/$repo_url
+    cd $git_dir/$user/$repo_url
+    branch=${PWD##*/}
+    git fetch origin
+    git pull origin $branch
 }
 
     # commands
     # add
     # list
     # switch
-"${CMDS[@]}"
-
+# run the command selected
+[[ -n "$CMD" ]] && "$CMD"
 
 # check:
 # - https://stackoverflow.com/questions/54367011/git-bare-repositories-worktrees-and-tracking-branches
@@ -143,7 +162,7 @@ switch() {
 # how to get remote branches
 # how to pull updates
 # to to switch to a commit
-  # git worktree add -b workbranch2 workbranch2 30abe6a
+  # git worktree add -b 38.6 38.6 30abe6a
 
 
 # git clone --bare git@github.com:team-telnyx/ansible.git .bare
@@ -155,3 +174,9 @@ switch() {
 
 # Gets all branches from origin
 # git fetch origin
+
+
+
+
+# g fetch origin before creating a branch
+# g fetch --all
diff --git a/desktop/bin/tmx b/desktop/bin/tmx
--- a/desktop/bin/tmx
+++ b/desktop/bin/tmx
@@ -2,23 +2,42 @@
 
 ################################################################################
 #                                 FILE INFO
-# run tmuxp with the correct environment
+CLI="""
+use: tmx
+short: manage tmux windows
+long: |
+  run tmuxp with the correct environment
+commands:
+  - use: kill
+    short: kill windows
+    aliases:
+      - k
+"""
 ################################################################################
 
+
 # TODO:
-# use boa and kill window mode
 # test for popup tmux
     # with ftb-tmux-popup or fzf-tmux
-
-# close existing window
+# kill existing window before opening a new one
 
 # change to local directory
 cd "$(dirname $0)"
 # load lib
 . ../lib/lib_tmx.sh
 . ../lib/lib_utils.sh
+# global variables
+LOG_LEVEL=3 # default is 1:NOTE
 
-main() {
+
+tmx() {
+    log DEBG "$FUNCNAME: $*"
+    # if arguments over 1 run subcommand
+    if [ $# -gt 0 ]; then
+        $@
+        exit
+    fi
+
     # default values
     service_env=${service_env:-"us-prod"}
 
@@ -28,13 +47,70 @@ main() {
     else
         service_env=${1:-"us-prod"}; shift
     fi
+
+    # kill existing window before opening a new one
+    kill_1w $service_env
+
     # get the service and env
     service=$(echo $service_env | cut -d'-' -f1)
     env=$(echo $service_env | cut -d'-' -f2)
 
-    log note " SERVER_1=${SERVER_1[${service_env}]} SERVER_2=${SERVER_2[${service_env}]} SERVER_3=${SERVER_3[${service_env}]} SERVER_4=${SERVER_4[${service_env}]} SERVICE=${service} ENV=${env} DISABLE_AUTO_TITLE='true' tmuxp load ${PROFILE[${service_env}]}"
+    log INFO " SERVER_1=${SERVER_1[${service_env}]} SERVER_2=${SERVER_2[${service_env}]} SERVER_3=${SERVER_3[${service_env}]} SERVER_4=${SERVER_4[${service_env}]} SERVICE=${service} ENV=${env} DISABLE_AUTO_TITLE='true' tmuxp load ${PROFILE[${service_env}]}"
     SERVER_1=${SERVER_1[${service_env}]} SERVER_2=${SERVER_2[${service_env}]} SERVER_3=${SERVER_3[${service_env}]} SERVER_4=${SERVER_4[${service_env}]} SERVICE=${service} ENV=${env} DISABLE_AUTO_TITLE='true' tmuxp load -a ${PROFILE[${service_env}]}
 }
 
 
-main "$@"
+tmx_kill() {
+    log DEBG "$FUNCNAME: $*"
+    # if arguments over 1 run subcommand
+    if [ $# -gt 0 ]; then
+        $@
+    fi
+
+    # Get the list of current tmux windows in the current session
+    windows=$(tmux list-windows -F '#I: #W')
+
+    # Use gum to fuzzy find and select windows to kill
+    selected_windows=$(echo "$windows" | gum choose --no-limit)
+
+    # Check if any windows were selected
+    if [ -z "$selected_windows" ]; then
+        log ERRO "No windows selected. Exiting."
+        exit
+    fi
+
+    # Confirm the selected windows to kill
+    log NOTE "You have selected the following windows to kill: \n $selected_windows"
+    if ! (gum confirm "kill these windows?"); then
+        log ERRO "Aborting." && exit
+    fi
+
+    # kill the selected windows
+    while IFS= read -r line; do
+        window_id=$(echo "$line" | cut -d: -f1)
+        tmux kill-window -t "$window_id"
+    done <<< "$selected_windows"
+
+    log INFO "Selected windows killd."
+}
+
+kill_1w() {
+    # kill the window with the specified name
+    window_name=$1
+    # Get the list of current tmux windows in the current session
+    windows=$(tmux list-windows -F '#I: #W')
+
+    # Find the window ID corresponding to the window name
+    window_id=$(echo "$windows" | grep ": $window_name" | cut -d: -f1)
+    if [ -z "$window_id" ]; then
+        log INFO "No old window found to restart: $window_name"
+        return
+    fi
+    # kill the specified window
+    tmux kill-window -t "$window_id"
+    log INFO "Window $window_name (ID: $window_id) is getting restarted."
+}
+
+
+# run the command selected
+[[ -n "$CMD" ]] && "$CMD"
